create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price INT NOT NULL 
);
insert into car (id, make, model, price) values (1, 'BMW', 'M3', 5);
insert into car (id, make, model, price) values (2, 'Honda', 'Odyssey', 83);
insert into car (id, make, model, price) values (3, 'Infiniti', 'QX56', 67);
insert into car (id, make, model, price) values (4, 'GMC', 'Savana 2500', 71);
insert into car (id, make, model, price) values (5, 'Chevrolet', 'G-Series 1500', 57);
insert into car (id, make, model, price) values (6, 'Pontiac', 'Firebird', 49);
insert into car (id, make, model, price) values (7, 'Chevrolet', 'Lumina APV', 100);
insert into car (id, make, model, price) values (8, 'GMC', '2500', 80);
insert into car (id, make, model, price) values (9, 'Lexus', 'IS-F', 82);
insert into car (id, make, model, price) values (10, 'Honda', 'Prelude', 50);
insert into car (id, make, model, price) values (11, 'Nissan', 'Pathfinder', 4);
insert into car (id, make, model, price) values (12, 'Nissan', 'Maxima', 12);
insert into car (id, make, model, price) values (13, 'BMW', '530', 29);
insert into car (id, make, model, price) values (14, 'Jeep', 'Liberty', 44);
insert into car (id, make, model, price) values (15, 'Volvo', 'S80', 39);
insert into car (id, make, model, price) values (16, 'Dodge', 'Dakota Club', 12);
insert into car (id, make, model, price) values (17, 'Buick', 'Rainier', 78);
insert into car (id, make, model, price) values (18, 'Mazda', 'Mazda6', 56);
insert into car (id, make, model, price) values (19, 'Dodge', 'Dakota Club', 3);
insert into car (id, make, model, price) values (20, 'Ford', 'F250', 15);
insert into car (id, make, model, price) values (21, 'Buick', 'Rendezvous', 29);
insert into car (id, make, model, price) values (22, 'Ferrari', '599 GTB Fiorano', 85);
insert into car (id, make, model, price) values (23, 'Infiniti', 'M', 1);
insert into car (id, make, model, price) values (24, 'BMW', '6 Series', 57);
insert into car (id, make, model, price) values (25, 'Lexus', 'LX', 81);
insert into car (id, make, model, price) values (26, 'Subaru', 'Impreza', 25);
insert into car (id, make, model, price) values (27, 'Chevrolet', 'Corvette', 65);
insert into car (id, make, model, price) values (28, 'Ford', 'Explorer', 22);
insert into car (id, make, model, price) values (29, 'Mitsubishi', 'Starion', 91);
insert into car (id, make, model, price) values (30, 'Mitsubishi', 'Eclipse', 49);
insert into car (id, make, model, price) values (31, 'Porsche', 'Boxster', 85);
insert into car (id, make, model, price) values (32, 'Toyota', 'Sienna', 32);
insert into car (id, make, model, price) values (33, 'GMC', 'Yukon XL 1500', 35);
insert into car (id, make, model, price) values (34, 'Hyundai', 'Elantra', 5);
insert into car (id, make, model, price) values (35, 'Toyota', 'TundraMax', 78);
insert into car (id, make, model, price) values (36, 'Kia', 'Spectra', 33);
insert into car (id, make, model, price) values (37, 'Mercury', 'Mariner', 34);
insert into car (id, make, model, price) values (38, 'Mazda', 'MX-5', 66);
insert into car (id, make, model, price) values (39, 'Subaru', 'Justy', 26);
insert into car (id, make, model, price) values (40, 'Volkswagen', 'Cabriolet', 53);
insert into car (id, make, model, price) values (41, 'Pontiac', 'Grand Prix', 94);
insert into car (id, make, model, price) values (42, 'Infiniti', 'Q', 45);
insert into car (id, make, model, price) values (43, 'MINI', 'Cooper Clubman', 32);
insert into car (id, make, model, price) values (44, 'Ford', 'Mustang', 38);
insert into car (id, make, model, price) values (45, 'Subaru', 'Justy', 76);
insert into car (id, make, model, price) values (46, 'Audi', 'A6', 88);
insert into car (id, make, model, price) values (47, 'Spyker', 'C8 Laviolette', 86);
insert into car (id, make, model, price) values (48, 'Nissan', 'Maxima', 81);
insert into car (id, make, model, price) values (49, 'Jeep', 'Grand Cherokee', 60);
insert into car (id, make, model, price) values (50, 'Land Rover', 'LR3', 24);
insert into car (id, make, model, price) values (51, 'Audi', 'A8', 44);
insert into car (id, make, model, price) values (52, 'Chrysler', 'Cirrus', 86);
insert into car (id, make, model, price) values (53, 'GMC', 'Sierra 1500', 3);
insert into car (id, make, model, price) values (54, 'Mercury', 'Grand Marquis', 4);
insert into car (id, make, model, price) values (55, 'Geo', 'Metro', 40);
insert into car (id, make, model, price) values (56, 'Volvo', 'S60', 60);
insert into car (id, make, model, price) values (57, 'Oldsmobile', 'Silhouette', 60);
insert into car (id, make, model, price) values (58, 'Lexus', 'RX', 43);
insert into car (id, make, model, price) values (59, 'Mazda', 'B-Series Plus', 63);
insert into car (id, make, model, price) values (60, 'Ford', 'Thunderbird', 11);
insert into car (id, make, model, price) values (61, 'GMC', '3500 Club Coupe', 17);
insert into car (id, make, model, price) values (62, 'Volvo', 'S70', 53);
insert into car (id, make, model, price) values (63, 'Pontiac', 'Fiero', 36);
insert into car (id, make, model, price) values (64, 'Nissan', '300ZX', 60);
insert into car (id, make, model, price) values (65, 'Volvo', 'XC70', 55);
insert into car (id, make, model, price) values (66, 'Dodge', 'Caravan', 82);
insert into car (id, make, model, price) values (67, 'Land Rover', 'Range Rover', 31);
insert into car (id, make, model, price) values (68, 'GMC', 'Savana 2500', 30);
insert into car (id, make, model, price) values (69, 'Porsche', '944', 78);
insert into car (id, make, model, price) values (70, 'Ford', 'Bronco', 73);
insert into car (id, make, model, price) values (71, 'Mazda', 'Familia', 85);
insert into car (id, make, model, price) values (72, 'Acura', 'TL', 68);
insert into car (id, make, model, price) values (73, 'Ford', 'GT500', 78);
insert into car (id, make, model, price) values (74, 'Ford', 'F350', 33);
insert into car (id, make, model, price) values (75, 'Suzuki', 'Samurai', 97);
insert into car (id, make, model, price) values (76, 'Ford', 'Thunderbird', 12);
insert into car (id, make, model, price) values (77, 'Lincoln', 'MKX', 22);
insert into car (id, make, model, price) values (78, 'Ford', 'Escort', 12);
insert into car (id, make, model, price) values (79, 'Chevrolet', 'Corvette', 6);
insert into car (id, make, model, price) values (80, 'Plymouth', 'Roadrunner', 73);
insert into car (id, make, model, price) values (81, 'Subaru', 'Leone', 72);
insert into car (id, make, model, price) values (82, 'Toyota', 'RAV4', 49);
insert into car (id, make, model, price) values (83, 'Ford', 'F-Series Super Duty', 26);
insert into car (id, make, model, price) values (84, 'Honda', 'Accord', 37);
insert into car (id, make, model, price) values (85, 'Maserati', 'Spyder', 8);
insert into car (id, make, model, price) values (86, 'Ford', 'GT', 76);
insert into car (id, make, model, price) values (87, 'Buick', 'LeSabre', 93);
insert into car (id, make, model, price) values (88, 'Nissan', 'Frontier', 5);
insert into car (id, make, model, price) values (89, 'Ford', 'F-Series', 58);
insert into car (id, make, model, price) values (90, 'GMC', 'Rally Wagon 2500', 79);
insert into car (id, make, model, price) values (91, 'Saab', '900', 71);
insert into car (id, make, model, price) values (92, 'Volvo', 'C70', 2);
insert into car (id, make, model, price) values (93, 'Pontiac', 'Grand Am', 3);
insert into car (id, make, model, price) values (94, 'Pontiac', 'Grand Prix', 32);
insert into car (id, make, model, price) values (95, 'Mazda', 'MX-5', 42);
insert into car (id, make, model, price) values (96, 'Volkswagen', 'Jetta', 94);
insert into car (id, make, model, price) values (97, 'Chevrolet', 'Aveo', 73);
insert into car (id, make, model, price) values (98, 'Infiniti', 'QX56', 66);
insert into car (id, make, model, price) values (99, 'Dodge', 'Dakota Club', 4);
insert into car (id, make, model, price) values (100, 'BMW', '5 Series', 24);
insert into car (id, make, model, price) values (101, 'Dodge', 'Caravan', 24);
insert into car (id, make, model, price) values (102, 'Aston Martin', 'V8 Vantage', 35);
insert into car (id, make, model, price) values (103, 'Honda', 'Fit', 71);
insert into car (id, make, model, price) values (104, 'Isuzu', 'Axiom', 99);
insert into car (id, make, model, price) values (105, 'Aston Martin', 'Vanquish S', 43);
insert into car (id, make, model, price) values (106, 'Saab', '9-3', 17);
insert into car (id, make, model, price) values (107, 'Chevrolet', 'Uplander', 81);
insert into car (id, make, model, price) values (108, 'Cadillac', 'Eldorado', 86);
insert into car (id, make, model, price) values (109, 'Honda', 'Accord', 43);
insert into car (id, make, model, price) values (110, 'Audi', 'S8', 58);
insert into car (id, make, model, price) values (111, 'Oldsmobile', 'Achieva', 37);
insert into car (id, make, model, price) values (112, 'Acura', 'RL', 92);
insert into car (id, make, model, price) values (113, 'Ford', 'E350', 66);
insert into car (id, make, model, price) values (114, 'Chrysler', '300', 43);
insert into car (id, make, model, price) values (115, 'Chevrolet', 'Corvette', 24);
insert into car (id, make, model, price) values (116, 'Ford', 'Thunderbird', 36);
insert into car (id, make, model, price) values (117, 'Nissan', 'Frontier', 34);
insert into car (id, make, model, price) values (118, 'Toyota', 'Camry Hybrid', 98);
insert into car (id, make, model, price) values (119, 'Hyundai', 'Elantra', 64);
insert into car (id, make, model, price) values (120, 'Cadillac', 'DeVille', 91);
insert into car (id, make, model, price) values (121, 'Pontiac', 'Firebird Formula', 26);
insert into car (id, make, model, price) values (122, 'BMW', '6 Series', 5);
insert into car (id, make, model, price) values (123, 'Isuzu', 'i-Series', 2);
insert into car (id, make, model, price) values (124, 'Cadillac', 'STS', 67);
insert into car (id, make, model, price) values (125, 'Dodge', 'Durango', 1);
insert into car (id, make, model, price) values (126, 'Ford', 'Fiesta', 3);
insert into car (id, make, model, price) values (127, 'Chevrolet', 'Corvette', 92);
insert into car (id, make, model, price) values (128, 'Audi', '90', 59);
insert into car (id, make, model, price) values (129, 'Mercedes-Benz', 'SLK-Class', 40);
insert into car (id, make, model, price) values (130, 'Buick', 'LeSabre', 19);
insert into car (id, make, model, price) values (131, 'Ford', 'Escape', 15);
insert into car (id, make, model, price) values (132, 'Audi', 'A6', 1);
insert into car (id, make, model, price) values (133, 'Ford', 'Aerostar', 75);
insert into car (id, make, model, price) values (134, 'Buick', 'Enclave', 68);
insert into car (id, make, model, price) values (135, 'Ford', 'Mustang', 59);
insert into car (id, make, model, price) values (136, 'Suzuki', 'Reno', 1);
insert into car (id, make, model, price) values (137, 'GMC', '3500 Club Coupe', 93);
insert into car (id, make, model, price) values (138, 'Pontiac', 'Grand Am', 85);
insert into car (id, make, model, price) values (139, 'Nissan', 'Sentra', 28);
insert into car (id, make, model, price) values (140, 'Pontiac', 'Firebird', 3);
insert into car (id, make, model, price) values (141, 'Mercedes-Benz', 'SLR McLaren', 50);
insert into car (id, make, model, price) values (142, 'Hyundai', 'Excel', 59);
insert into car (id, make, model, price) values (143, 'Pontiac', 'Grand Prix', 1);
insert into car (id, make, model, price) values (144, 'Pontiac', 'G6', 33);
insert into car (id, make, model, price) values (145, 'Mercury', 'Grand Marquis', 62);
insert into car (id, make, model, price) values (146, 'Pontiac', 'Grand Am', 34);
insert into car (id, make, model, price) values (147, 'Kia', 'Sportage', 12);
insert into car (id, make, model, price) values (148, 'Volvo', '850', 34);
insert into car (id, make, model, price) values (149, 'Suzuki', 'Aerio', 21);
insert into car (id, make, model, price) values (150, 'Suzuki', 'SJ', 35);
insert into car (id, make, model, price) values (151, 'Lexus', 'RX Hybrid', 43);
insert into car (id, make, model, price) values (152, 'Toyota', 'Tacoma Xtra', 30);
insert into car (id, make, model, price) values (153, 'GMC', 'Savana 1500', 4);
insert into car (id, make, model, price) values (154, 'Toyota', 'Previa', 84);
insert into car (id, make, model, price) values (155, 'Lexus', 'IS', 93);
insert into car (id, make, model, price) values (156, 'Honda', 'Accord', 7);
insert into car (id, make, model, price) values (157, 'Kia', 'Amanti', 53);
insert into car (id, make, model, price) values (158, 'Toyota', 'Camry', 31);
insert into car (id, make, model, price) values (159, 'Porsche', '911', 27);
insert into car (id, make, model, price) values (160, 'Plymouth', 'Grand Voyager', 24);
insert into car (id, make, model, price) values (161, 'Dodge', 'Magnum', 97);
insert into car (id, make, model, price) values (162, 'Lexus', 'GS', 20);
insert into car (id, make, model, price) values (163, 'Kia', 'Sportage', 71);
insert into car (id, make, model, price) values (164, 'BMW', 'X6', 52);
insert into car (id, make, model, price) values (165, 'Chevrolet', 'Silverado 1500', 57);
insert into car (id, make, model, price) values (166, 'Chevrolet', 'Blazer', 28);
insert into car (id, make, model, price) values (167, 'Rolls-Royce', 'Ghost', 50);
insert into car (id, make, model, price) values (168, 'Jeep', 'Liberty', 11);
insert into car (id, make, model, price) values (169, 'Mercury', 'Lynx', 12);
insert into car (id, make, model, price) values (170, 'Mitsubishi', 'Endeavor', 41);
insert into car (id, make, model, price) values (171, 'Volvo', '960', 51);
insert into car (id, make, model, price) values (172, 'BMW', 'Z3', 100);
insert into car (id, make, model, price) values (173, 'Saab', '900', 28);
insert into car (id, make, model, price) values (174, 'Land Rover', 'Range Rover', 65);
insert into car (id, make, model, price) values (175, 'Mercedes-Benz', '400SE', 46);
insert into car (id, make, model, price) values (176, 'Infiniti', 'QX', 30);
insert into car (id, make, model, price) values (177, 'Ford', 'Ranger', 8);
insert into car (id, make, model, price) values (178, 'Mitsubishi', 'GTO', 40);
insert into car (id, make, model, price) values (179, 'Audi', 'V8', 4);
insert into car (id, make, model, price) values (180, 'Volkswagen', 'New Beetle', 50);
insert into car (id, make, model, price) values (181, 'Ford', 'Club Wagon', 66);
insert into car (id, make, model, price) values (182, 'Hyundai', 'Elantra', 90);
insert into car (id, make, model, price) values (183, 'Lexus', 'IS', 56);
insert into car (id, make, model, price) values (184, 'Honda', 'Prelude', 33);
insert into car (id, make, model, price) values (185, 'GMC', '2500', 7);
insert into car (id, make, model, price) values (186, 'Ford', 'F-Series Super Duty', 35);
insert into car (id, make, model, price) values (187, 'Mazda', 'Protege', 75);
insert into car (id, make, model, price) values (188, 'Honda', 'S2000', 75);
insert into car (id, make, model, price) values (189, 'Ford', 'F250', 12);
insert into car (id, make, model, price) values (190, 'Mercury', 'Mystique', 48);
insert into car (id, make, model, price) values (191, 'Mitsubishi', 'Mirage', 35);
insert into car (id, make, model, price) values (192, 'GMC', 'Savana 1500', 45);
insert into car (id, make, model, price) values (193, 'Volkswagen', 'Touareg', 56);
insert into car (id, make, model, price) values (194, 'Mercedes-Benz', 'E-Class', 88);
insert into car (id, make, model, price) values (195, 'Kia', 'Rio', 3);
insert into car (id, make, model, price) values (196, 'Toyota', 'Avalon', 44);
insert into car (id, make, model, price) values (197, 'Pontiac', 'Firebird', 39);
insert into car (id, make, model, price) values (198, 'GMC', 'Sierra 3500HD', 80);
insert into car (id, make, model, price) values (199, 'Oldsmobile', 'Bravada', 89);
insert into car (id, make, model, price) values (200, 'Chevrolet', 'G-Series G30', 80);
insert into car (id, make, model, price) values (201, 'Mercury', 'Marauder', 81);
insert into car (id, make, model, price) values (202, 'Toyota', 'Solara', 9);
insert into car (id, make, model, price) values (203, 'Audi', 'A4', 34);
insert into car (id, make, model, price) values (204, 'Chevrolet', 'Express 2500', 37);
insert into car (id, make, model, price) values (205, 'Mercedes-Benz', 'G-Class', 78);
insert into car (id, make, model, price) values (206, 'Rolls-Royce', 'Phantom', 51);
insert into car (id, make, model, price) values (207, 'Nissan', 'Quest', 45);
insert into car (id, make, model, price) values (208, 'Buick', 'Lucerne', 70);
insert into car (id, make, model, price) values (209, 'Mazda', 'Miata MX-5', 18);
insert into car (id, make, model, price) values (210, 'Ford', 'Crown Victoria', 88);
insert into car (id, make, model, price) values (211, 'Mazda', 'Tribute', 32);
insert into car (id, make, model, price) values (212, 'Chevrolet', 'Uplander', 33);
insert into car (id, make, model, price) values (213, 'Lotus', 'Esprit', 68);
insert into car (id, make, model, price) values (214, 'Dodge', 'Ram Van 1500', 80);
insert into car (id, make, model, price) values (215, 'GMC', 'Yukon XL 2500', 76);
insert into car (id, make, model, price) values (216, 'Buick', 'LeSabre', 9);
insert into car (id, make, model, price) values (217, 'Mazda', 'MX-6', 3);
insert into car (id, make, model, price) values (218, 'Volkswagen', 'GTI', 63);
insert into car (id, make, model, price) values (219, 'Dodge', 'Neon', 1);
insert into car (id, make, model, price) values (220, 'Lexus', 'SC', 14);
insert into car (id, make, model, price) values (221, 'BMW', '7 Series', 84);
insert into car (id, make, model, price) values (222, 'GMC', 'Yukon Denali', 41);
insert into car (id, make, model, price) values (223, 'Cadillac', 'Catera', 85);
insert into car (id, make, model, price) values (224, 'Toyota', 'MR2', 72);
insert into car (id, make, model, price) values (225, 'Lexus', 'GS', 83);
insert into car (id, make, model, price) values (226, 'Mitsubishi', 'Excel', 98);
insert into car (id, make, model, price) values (227, 'Mercury', 'Monterey', 59);
insert into car (id, make, model, price) values (228, 'Chevrolet', 'Silverado 2500', 68);
insert into car (id, make, model, price) values (229, 'Mercury', 'Tracer', 2);
insert into car (id, make, model, price) values (230, 'Ford', 'Escape', 98);
insert into car (id, make, model, price) values (231, 'Mercedes-Benz', 'SLS AMG', 35);
insert into car (id, make, model, price) values (232, 'Audi', '5000CS Quattro', 94);
insert into car (id, make, model, price) values (233, 'Ford', 'E-Series', 94);
insert into car (id, make, model, price) values (234, 'Cadillac', 'Seville', 69);
insert into car (id, make, model, price) values (235, 'Honda', 'Civic', 50);
insert into car (id, make, model, price) values (236, 'Chevrolet', 'Aveo', 86);
insert into car (id, make, model, price) values (237, 'Honda', 'Ridgeline', 19);
insert into car (id, make, model, price) values (238, 'Chevrolet', 'Corsica', 76);
insert into car (id, make, model, price) values (239, 'Toyota', 'Tacoma', 47);
insert into car (id, make, model, price) values (240, 'GMC', 'Yukon', 98);
insert into car (id, make, model, price) values (241, 'Cadillac', 'Catera', 31);
insert into car (id, make, model, price) values (242, 'Chevrolet', 'Caprice', 90);
insert into car (id, make, model, price) values (243, 'BMW', '760', 72);
insert into car (id, make, model, price) values (244, 'Subaru', 'XT', 60);
insert into car (id, make, model, price) values (245, 'Cadillac', 'Seville', 80);
insert into car (id, make, model, price) values (246, 'Chevrolet', '2500', 69);
insert into car (id, make, model, price) values (247, 'Volkswagen', 'Tiguan', 78);
insert into car (id, make, model, price) values (248, 'Ford', 'E-Series', 13);
insert into car (id, make, model, price) values (249, 'Dodge', 'Viper', 100);
insert into car (id, make, model, price) values (250, 'Toyota', 'Tundra', 32);
insert into car (id, make, model, price) values (251, 'Ford', 'Edge', 64);
insert into car (id, make, model, price) values (252, 'Volkswagen', 'Type 2', 98);
insert into car (id, make, model, price) values (253, 'Pontiac', 'Trans Sport', 2);
insert into car (id, make, model, price) values (254, 'Hyundai', 'Excel', 45);
insert into car (id, make, model, price) values (255, 'Infiniti', 'G', 81);
insert into car (id, make, model, price) values (256, 'Volkswagen', 'Tiguan', 26);
insert into car (id, make, model, price) values (257, 'Cadillac', 'Escalade EXT', 5);
insert into car (id, make, model, price) values (258, 'Acura', 'RDX', 15);
insert into car (id, make, model, price) values (259, 'Oldsmobile', 'Bravada', 88);
insert into car (id, make, model, price) values (260, 'Buick', 'Electra', 72);
insert into car (id, make, model, price) values (261, 'Dodge', 'Grand Caravan', 64);
insert into car (id, make, model, price) values (262, 'Lexus', 'HS', 54);
insert into car (id, make, model, price) values (263, 'Land Rover', 'Range Rover', 7);
insert into car (id, make, model, price) values (264, 'Saab', '9-3', 23);
insert into car (id, make, model, price) values (265, 'Dodge', 'Shadow', 23);
insert into car (id, make, model, price) values (266, 'Chevrolet', 'Malibu', 60);
insert into car (id, make, model, price) values (267, 'Cadillac', 'CTS', 99);
insert into car (id, make, model, price) values (268, 'GMC', 'Rally Wagon 2500', 39);
insert into car (id, make, model, price) values (269, 'Maybach', 'Landaulet', 19);
insert into car (id, make, model, price) values (270, 'Saturn', 'VUE', 84);
insert into car (id, make, model, price) values (271, 'Toyota', 'RAV4', 65);
insert into car (id, make, model, price) values (272, 'Dodge', 'Ram', 59);
insert into car (id, make, model, price) values (273, 'Saab', '9-5', 37);
insert into car (id, make, model, price) values (274, 'Ford', 'Crown Victoria', 59);
insert into car (id, make, model, price) values (275, 'Oldsmobile', 'Ciera', 83);
insert into car (id, make, model, price) values (276, 'Mazda', 'Navajo', 15);
insert into car (id, make, model, price) values (277, 'Volkswagen', 'Golf', 66);
insert into car (id, make, model, price) values (278, 'Mazda', 'RX-7', 84);
insert into car (id, make, model, price) values (279, 'Audi', 'S8', 41);
insert into car (id, make, model, price) values (280, 'Porsche', '928', 64);
insert into car (id, make, model, price) values (281, 'Bentley', 'Continental Flying Spur', 64);
insert into car (id, make, model, price) values (282, 'Ford', 'E150', 55);
insert into car (id, make, model, price) values (283, 'Lexus', 'ES', 3);
insert into car (id, make, model, price) values (284, 'Chevrolet', 'G-Series 3500', 94);
insert into car (id, make, model, price) values (285, 'Oldsmobile', '88', 52);
insert into car (id, make, model, price) values (286, 'Hyundai', 'Equus', 58);
insert into car (id, make, model, price) values (287, 'Volkswagen', 'Jetta', 64);
insert into car (id, make, model, price) values (288, 'Plymouth', 'Grand Voyager', 76);
insert into car (id, make, model, price) values (289, 'Ford', 'Five Hundred', 52);
insert into car (id, make, model, price) values (290, 'Pontiac', 'Firebird Trans Am', 29);
insert into car (id, make, model, price) values (291, 'Ford', 'Tempo', 16);
insert into car (id, make, model, price) values (292, 'Mercury', 'Sable', 45);
insert into car (id, make, model, price) values (293, 'Toyota', 'Camry', 100);
insert into car (id, make, model, price) values (294, 'Chevrolet', 'Corvette', 83);
insert into car (id, make, model, price) values (295, 'Ford', 'Bronco', 71);
insert into car (id, make, model, price) values (296, 'Ford', 'Econoline E150', 82);
insert into car (id, make, model, price) values (297, 'Kia', 'Soul', 70);
insert into car (id, make, model, price) values (298, 'Mitsubishi', 'Pajero', 10);
insert into car (id, make, model, price) values (299, 'Mitsubishi', 'Endeavor', 23);
insert into car (id, make, model, price) values (300, 'Mercedes-Benz', 'E-Class', 65);
insert into car (id, make, model, price) values (301, 'Chevrolet', 'Suburban 1500', 2);
insert into car (id, make, model, price) values (302, 'Toyota', 'Highlander', 36);
insert into car (id, make, model, price) values (303, 'Infiniti', 'Q', 40);
insert into car (id, make, model, price) values (304, 'Pontiac', 'Firebird', 56);
insert into car (id, make, model, price) values (305, 'Land Rover', 'Defender', 43);
insert into car (id, make, model, price) values (306, 'Jeep', 'Liberty', 13);
insert into car (id, make, model, price) values (307, 'Nissan', '200SX', 60);
insert into car (id, make, model, price) values (308, 'Chevrolet', 'Equinox', 97);
insert into car (id, make, model, price) values (309, 'Chevrolet', 'Camaro', 29);
insert into car (id, make, model, price) values (310, 'Porsche', 'Boxster', 56);
insert into car (id, make, model, price) values (311, 'Chevrolet', 'Avalanche 2500', 87);
insert into car (id, make, model, price) values (312, 'Nissan', 'Altima', 79);
insert into car (id, make, model, price) values (313, 'Mercedes-Benz', 'S-Class', 1);
insert into car (id, make, model, price) values (314, 'Shelby', 'GT350', 35);
insert into car (id, make, model, price) values (315, 'Suzuki', 'Samurai', 78);
insert into car (id, make, model, price) values (316, 'Pontiac', 'Firebird', 15);
insert into car (id, make, model, price) values (317, 'MINI', 'Cooper Clubman', 13);
insert into car (id, make, model, price) values (318, 'GMC', 'Safari', 50);
insert into car (id, make, model, price) values (319, 'Jeep', 'Grand Cherokee', 4);
insert into car (id, make, model, price) values (320, 'Mazda', 'Mazda3', 40);
insert into car (id, make, model, price) values (321, 'Chrysler', 'Sebring', 49);
insert into car (id, make, model, price) values (322, 'Infiniti', 'J', 83);
insert into car (id, make, model, price) values (323, 'Infiniti', 'EX', 81);
insert into car (id, make, model, price) values (324, 'Ford', 'Aerostar', 49);
insert into car (id, make, model, price) values (325, 'Toyota', 'Corolla', 92);
insert into car (id, make, model, price) values (326, 'Mercedes-Benz', 'SL-Class', 96);
insert into car (id, make, model, price) values (327, 'Hyundai', 'Accent', 56);
insert into car (id, make, model, price) values (328, 'Oldsmobile', 'Regency', 2);
insert into car (id, make, model, price) values (329, 'Dodge', 'Stealth', 85);
insert into car (id, make, model, price) values (330, 'Land Rover', 'Defender', 27);
insert into car (id, make, model, price) values (331, 'Toyota', 'Yaris', 20);
insert into car (id, make, model, price) values (332, 'Toyota', 'Avalon', 70);
insert into car (id, make, model, price) values (333, 'Cadillac', 'Seville', 73);
insert into car (id, make, model, price) values (334, 'Dodge', 'Ram Van 2500', 55);
insert into car (id, make, model, price) values (335, 'Mazda', '626', 47);
insert into car (id, make, model, price) values (336, 'Land Rover', 'LR3', 5);
insert into car (id, make, model, price) values (337, 'Volkswagen', 'Jetta', 44);
insert into car (id, make, model, price) values (338, 'Ford', 'E-Series', 2);
insert into car (id, make, model, price) values (339, 'Dodge', 'Viper', 83);
insert into car (id, make, model, price) values (340, 'Mercury', 'Tracer', 88);
insert into car (id, make, model, price) values (341, 'Volkswagen', 'Rabbit', 30);
insert into car (id, make, model, price) values (342, 'Pontiac', 'Grand Prix', 2);
insert into car (id, make, model, price) values (343, 'GMC', 'Savana 1500', 85);
insert into car (id, make, model, price) values (344, 'Dodge', 'Ram Van B250', 64);
insert into car (id, make, model, price) values (345, 'GMC', 'Vandura 3500', 16);
insert into car (id, make, model, price) values (346, 'Mazda', 'MX-3', 46);
insert into car (id, make, model, price) values (347, 'Isuzu', 'Space', 47);
insert into car (id, make, model, price) values (348, 'Bentley', 'Continental GT', 59);
insert into car (id, make, model, price) values (349, 'Mitsubishi', 'Mirage', 22);
insert into car (id, make, model, price) values (350, 'Ford', 'EXP', 100);
insert into car (id, make, model, price) values (351, 'Mazda', 'B2600', 28);
insert into car (id, make, model, price) values (352, 'Chevrolet', 'Express 2500', 69);
insert into car (id, make, model, price) values (353, 'Mercury', 'Sable', 40);
insert into car (id, make, model, price) values (354, 'Honda', 'Civic', 42);
insert into car (id, make, model, price) values (355, 'Ford', 'Crown Victoria', 56);
insert into car (id, make, model, price) values (356, 'Chevrolet', 'Avalanche', 45);
insert into car (id, make, model, price) values (357, 'GMC', 'Yukon', 38);
insert into car (id, make, model, price) values (358, 'GMC', '3500', 16);
insert into car (id, make, model, price) values (359, 'Acura', 'ZDX', 46);
insert into car (id, make, model, price) values (360, 'Suzuki', 'Esteem', 72);
insert into car (id, make, model, price) values (361, 'Pontiac', '1000', 19);
insert into car (id, make, model, price) values (362, 'Toyota', 'RAV4', 30);
insert into car (id, make, model, price) values (363, 'Chevrolet', 'Aveo', 70);
insert into car (id, make, model, price) values (364, 'Chevrolet', 'Impala', 82);
insert into car (id, make, model, price) values (365, 'Suzuki', 'Swift', 28);
insert into car (id, make, model, price) values (366, 'Infiniti', 'QX', 48);
insert into car (id, make, model, price) values (367, 'GMC', 'Savana 1500', 25);
insert into car (id, make, model, price) values (368, 'BMW', '525', 73);
insert into car (id, make, model, price) values (369, 'Acura', 'NSX', 72);
insert into car (id, make, model, price) values (370, 'Volkswagen', 'Jetta', 16);
insert into car (id, make, model, price) values (371, 'GMC', 'Rally Wagon 2500', 70);
insert into car (id, make, model, price) values (372, 'Jeep', 'Cherokee', 5);
insert into car (id, make, model, price) values (373, 'Eagle', 'Premier', 78);
insert into car (id, make, model, price) values (374, 'Buick', 'Terraza', 24);
insert into car (id, make, model, price) values (375, 'Volkswagen', 'Passat', 10);
insert into car (id, make, model, price) values (376, 'BMW', 'X5 M', 19);
insert into car (id, make, model, price) values (377, 'Honda', 'Civic', 78);
insert into car (id, make, model, price) values (378, 'Pontiac', 'Sunfire', 79);
insert into car (id, make, model, price) values (379, 'Dodge', 'Ram 1500 Club', 80);
insert into car (id, make, model, price) values (380, 'Ford', 'Expedition', 93);
insert into car (id, make, model, price) values (381, 'Mercedes-Benz', '600SEC', 5);
insert into car (id, make, model, price) values (382, 'Kia', 'Sorento', 2);
insert into car (id, make, model, price) values (383, 'Ford', 'Mustang', 59);
insert into car (id, make, model, price) values (384, 'Hyundai', 'Elantra', 16);
insert into car (id, make, model, price) values (385, 'Audi', 'TT', 36);
insert into car (id, make, model, price) values (386, 'Aston Martin', 'V8 Vantage', 33);
insert into car (id, make, model, price) values (387, 'Pontiac', 'Bonneville', 45);
insert into car (id, make, model, price) values (388, 'Buick', 'LeSabre', 4);
insert into car (id, make, model, price) values (389, 'Mercedes-Benz', 'S-Class', 25);
insert into car (id, make, model, price) values (390, 'Dodge', 'Ram 2500 Club', 35);
insert into car (id, make, model, price) values (391, 'Acura', 'NSX', 87);
insert into car (id, make, model, price) values (392, 'Maserati', 'GranSport', 11);
insert into car (id, make, model, price) values (393, 'Lincoln', 'Continental', 54);
insert into car (id, make, model, price) values (394, 'Smart', 'Fortwo', 62);
insert into car (id, make, model, price) values (395, 'Buick', 'Century', 63);
insert into car (id, make, model, price) values (396, 'Chevrolet', 'Silverado 3500', 31);
insert into car (id, make, model, price) values (397, 'Ford', 'Ranger', 49);
insert into car (id, make, model, price) values (398, 'Volkswagen', 'CC', 40);
insert into car (id, make, model, price) values (399, 'Audi', '5000CS', 30);
insert into car (id, make, model, price) values (400, 'Suzuki', 'Aerio', 18);
insert into car (id, make, model, price) values (401, 'Honda', 'Civic GX', 27);
insert into car (id, make, model, price) values (402, 'Mazda', 'RX-8', 95);
insert into car (id, make, model, price) values (403, 'Chevrolet', 'G-Series 2500', 88);
insert into car (id, make, model, price) values (404, 'Cadillac', 'Escalade EXT', 24);
insert into car (id, make, model, price) values (405, 'Hyundai', 'Azera', 31);
insert into car (id, make, model, price) values (406, 'Mitsubishi', 'Space', 41);
insert into car (id, make, model, price) values (407, 'Ford', 'Escort', 93);
insert into car (id, make, model, price) values (408, 'Kia', 'Optima', 93);
insert into car (id, make, model, price) values (409, 'Cadillac', 'DeVille', 82);
insert into car (id, make, model, price) values (410, 'Daewoo', 'Leganza', 48);
insert into car (id, make, model, price) values (411, 'Ford', 'Focus', 83);
insert into car (id, make, model, price) values (412, 'Mitsubishi', 'Truck', 51);
insert into car (id, make, model, price) values (413, 'Cadillac', 'Escalade', 22);
insert into car (id, make, model, price) values (414, 'Lincoln', 'LS', 95);
insert into car (id, make, model, price) values (415, 'Volkswagen', 'Golf', 78);
insert into car (id, make, model, price) values (416, 'Lincoln', 'LS', 80);
insert into car (id, make, model, price) values (417, 'Volkswagen', 'GTI', 28);
insert into car (id, make, model, price) values (418, 'Chevrolet', 'Caprice', 90);
insert into car (id, make, model, price) values (419, 'Suzuki', 'Equator', 73);
insert into car (id, make, model, price) values (420, 'Infiniti', 'IPL G', 68);
insert into car (id, make, model, price) values (421, 'Kia', 'Optima', 88);
insert into car (id, make, model, price) values (422, 'Hummer', 'H3T', 48);
insert into car (id, make, model, price) values (423, 'Audi', 'S5', 41);
insert into car (id, make, model, price) values (424, 'Buick', 'LaCrosse', 90);
insert into car (id, make, model, price) values (425, 'Tesla', 'Model S', 51);
insert into car (id, make, model, price) values (426, 'Suzuki', 'Forenza', 98);
insert into car (id, make, model, price) values (427, 'GMC', 'Sierra', 62);
insert into car (id, make, model, price) values (428, 'Buick', 'Century', 49);
insert into car (id, make, model, price) values (429, 'Chevrolet', 'Sonic', 79);
insert into car (id, make, model, price) values (430, 'Dodge', 'Ram Van 1500', 36);
insert into car (id, make, model, price) values (431, 'Chevrolet', 'Cobalt SS', 42);
insert into car (id, make, model, price) values (432, 'Pontiac', 'Grand Prix', 22);
insert into car (id, make, model, price) values (433, 'Mercedes-Benz', 'CLS-Class', 69);
insert into car (id, make, model, price) values (434, 'Ford', 'Expedition EL', 50);
insert into car (id, make, model, price) values (435, 'Audi', 'S5', 43);
insert into car (id, make, model, price) values (436, 'Kia', 'Sportage', 3);
insert into car (id, make, model, price) values (437, 'Dodge', 'Ram 3500 Club', 8);
insert into car (id, make, model, price) values (438, 'Lexus', 'ES', 66);
insert into car (id, make, model, price) values (439, 'Peugeot', '207', 79);
insert into car (id, make, model, price) values (440, 'BMW', '330', 79);
insert into car (id, make, model, price) values (441, 'Volvo', 'C70', 51);
insert into car (id, make, model, price) values (442, 'Buick', 'Riviera', 91);
insert into car (id, make, model, price) values (443, 'Pontiac', 'GTO', 21);
insert into car (id, make, model, price) values (444, 'GMC', '2500 Club Coupe', 66);
insert into car (id, make, model, price) values (445, 'Dodge', 'Charger', 43);
insert into car (id, make, model, price) values (446, 'Geo', 'Prizm', 45);
insert into car (id, make, model, price) values (447, 'Chrysler', '300', 41);
insert into car (id, make, model, price) values (448, 'Bentley', 'Continental GTC', 64);
insert into car (id, make, model, price) values (449, 'Hyundai', 'Elantra', 67);
insert into car (id, make, model, price) values (450, 'Mercedes-Benz', 'CL65 AMG', 40);
insert into car (id, make, model, price) values (451, 'Mercury', 'Mountaineer', 52);
insert into car (id, make, model, price) values (452, 'Honda', 'Element', 94);
insert into car (id, make, model, price) values (453, 'Dodge', 'Viper', 34);
insert into car (id, make, model, price) values (454, 'GMC', 'Envoy', 18);
insert into car (id, make, model, price) values (455, 'Lincoln', 'Navigator', 16);
insert into car (id, make, model, price) values (456, 'Nissan', 'Xterra', 99);
insert into car (id, make, model, price) values (457, 'Toyota', 'Tacoma', 98);
insert into car (id, make, model, price) values (458, 'Ford', 'Bronco II', 94);
insert into car (id, make, model, price) values (459, 'Infiniti', 'G', 67);
insert into car (id, make, model, price) values (460, 'Porsche', 'Cayenne', 94);
insert into car (id, make, model, price) values (461, 'Suzuki', 'Sidekick', 96);
insert into car (id, make, model, price) values (462, 'Dodge', 'Caliber', 41);
insert into car (id, make, model, price) values (463, 'Audi', 'Coupe Quattro', 22);
insert into car (id, make, model, price) values (464, 'Chevrolet', 'Suburban 2500', 13);
insert into car (id, make, model, price) values (465, 'Mazda', '929', 18);
insert into car (id, make, model, price) values (466, 'Nissan', 'Titan', 69);
insert into car (id, make, model, price) values (467, 'Hyundai', 'Accent', 15);
insert into car (id, make, model, price) values (468, 'Mercedes-Benz', 'G-Class', 9);
insert into car (id, make, model, price) values (469, 'Chevrolet', 'Cobalt', 91);
insert into car (id, make, model, price) values (470, 'Land Rover', 'LR2', 88);
insert into car (id, make, model, price) values (471, 'Mercury', 'Mariner', 47);
insert into car (id, make, model, price) values (472, 'Chevrolet', 'Cavalier', 87);
insert into car (id, make, model, price) values (473, 'Infiniti', 'FX', 62);
insert into car (id, make, model, price) values (474, 'Dodge', 'Dakota Club', 45);
insert into car (id, make, model, price) values (475, 'Buick', 'Century', 80);
insert into car (id, make, model, price) values (476, 'Jeep', 'Grand Cherokee', 23);
insert into car (id, make, model, price) values (477, 'GMC', 'Savana 1500', 5);
insert into car (id, make, model, price) values (478, 'Suzuki', 'Esteem', 11);
insert into car (id, make, model, price) values (479, 'Volvo', '960', 85);
insert into car (id, make, model, price) values (480, 'Land Rover', 'LR2', 12);
insert into car (id, make, model, price) values (481, 'BMW', 'Z4', 46);
insert into car (id, make, model, price) values (482, 'Infiniti', 'Q', 78);
insert into car (id, make, model, price) values (483, 'Lexus', 'LX', 1);
insert into car (id, make, model, price) values (484, 'Porsche', '968', 77);
insert into car (id, make, model, price) values (485, 'Jeep', 'Wrangler', 61);
insert into car (id, make, model, price) values (486, 'Honda', 'Accord', 74);
insert into car (id, make, model, price) values (487, 'Chevrolet', 'Tahoe', 100);
insert into car (id, make, model, price) values (488, 'Ford', 'F150', 10);
insert into car (id, make, model, price) values (489, 'Mercedes-Benz', 'E-Class', 82);
insert into car (id, make, model, price) values (490, 'Toyota', 'Corolla', 66);
insert into car (id, make, model, price) values (491, 'Pontiac', 'Grand Am', 93);
insert into car (id, make, model, price) values (492, 'Volvo', 'V70', 29);
insert into car (id, make, model, price) values (493, 'Volvo', 'S40', 51);
insert into car (id, make, model, price) values (494, 'Mitsubishi', 'Pajero', 70);
insert into car (id, make, model, price) values (495, 'Toyota', 'Camry', 88);
insert into car (id, make, model, price) values (496, 'Toyota', 'Prius', 1);
insert into car (id, make, model, price) values (497, 'Pontiac', 'Vibe', 49);
insert into car (id, make, model, price) values (498, 'Lotus', 'Exige', 45);
insert into car (id, make, model, price) values (499, 'Mazda', 'Miata MX-5', 87);
insert into car (id, make, model, price) values (500, 'Chevrolet', 'Metro', 91);
insert into car (id, make, model, price) values (501, 'Cadillac', 'Escalade EXT', 94);
insert into car (id, make, model, price) values (502, 'BMW', 'X3', 92);
insert into car (id, make, model, price) values (503, 'Mercedes-Benz', 'C-Class', 87);
insert into car (id, make, model, price) values (504, 'Mazda', 'Protege5', 36);
insert into car (id, make, model, price) values (505, 'Mazda', 'Tribute', 92);
insert into car (id, make, model, price) values (506, 'Ford', 'E250', 47);
insert into car (id, make, model, price) values (507, 'Lexus', 'SC', 88);
insert into car (id, make, model, price) values (508, 'Mazda', 'B-Series', 56);
insert into car (id, make, model, price) values (509, 'Mazda', 'RX-7', 43);
insert into car (id, make, model, price) values (510, 'BMW', '7 Series', 93);
insert into car (id, make, model, price) values (511, 'Chevrolet', 'Suburban 2500', 68);
insert into car (id, make, model, price) values (512, 'Lotus', 'Elise', 57);
insert into car (id, make, model, price) values (513, 'Mercedes-Benz', 'M-Class', 95);
insert into car (id, make, model, price) values (514, 'Subaru', 'Justy', 33);
insert into car (id, make, model, price) values (515, 'BMW', '530', 54);
insert into car (id, make, model, price) values (516, 'Honda', 'Insight', 80);
insert into car (id, make, model, price) values (517, 'GMC', 'Safari', 18);
insert into car (id, make, model, price) values (518, 'Dodge', 'Durango', 10);
insert into car (id, make, model, price) values (519, 'Lexus', 'SC', 4);
insert into car (id, make, model, price) values (520, 'Shelby', 'GT500', 85);
insert into car (id, make, model, price) values (521, 'Oldsmobile', '88', 20);
insert into car (id, make, model, price) values (522, 'Nissan', 'Altima', 49);
insert into car (id, make, model, price) values (523, 'Ford', 'Taurus', 46);
insert into car (id, make, model, price) values (524, 'Honda', 'Odyssey', 32);
insert into car (id, make, model, price) values (525, 'Lotus', 'Esprit', 8);
insert into car (id, make, model, price) values (526, 'BMW', '645', 93);
insert into car (id, make, model, price) values (527, 'Mercedes-Benz', '300SL', 99);
insert into car (id, make, model, price) values (528, 'Mercury', 'Sable', 43);
insert into car (id, make, model, price) values (529, 'Honda', 'Odyssey', 80);
insert into car (id, make, model, price) values (530, 'Chrysler', '300M', 73);
insert into car (id, make, model, price) values (531, 'Land Rover', 'LR2', 4);
insert into car (id, make, model, price) values (532, 'Mazda', 'MX-5', 59);
insert into car (id, make, model, price) values (533, 'Ford', 'Flex', 62);
insert into car (id, make, model, price) values (534, 'Maserati', 'Spyder', 38);
insert into car (id, make, model, price) values (535, 'Isuzu', 'Ascender', 69);
insert into car (id, make, model, price) values (536, 'Audi', '5000S', 66);
insert into car (id, make, model, price) values (537, 'Chevrolet', 'Camaro', 9);
insert into car (id, make, model, price) values (538, 'Cadillac', 'Fleetwood', 90);
insert into car (id, make, model, price) values (539, 'Mitsubishi', 'Diamante', 47);
insert into car (id, make, model, price) values (540, 'Volkswagen', 'Tiguan', 98);
insert into car (id, make, model, price) values (541, 'Saturn', 'L-Series', 94);
insert into car (id, make, model, price) values (542, 'Plymouth', 'Laser', 85);
insert into car (id, make, model, price) values (543, 'Pontiac', 'Gemini', 66);
insert into car (id, make, model, price) values (544, 'Honda', 'Accord', 32);
insert into car (id, make, model, price) values (545, 'Kia', 'Optima', 77);
insert into car (id, make, model, price) values (546, 'Mercedes-Benz', 'E-Class', 69);
insert into car (id, make, model, price) values (547, 'Alfa Romeo', 'Spider', 13);
insert into car (id, make, model, price) values (548, 'Cadillac', 'DTS', 68);
insert into car (id, make, model, price) values (549, 'Isuzu', 'Amigo', 44);
insert into car (id, make, model, price) values (550, 'Isuzu', 'Trooper', 8);
insert into car (id, make, model, price) values (551, 'Oldsmobile', 'Cutlass Cruiser', 28);
insert into car (id, make, model, price) values (552, 'Suzuki', 'Kizashi', 22);
insert into car (id, make, model, price) values (553, 'Ford', 'Focus', 53);
insert into car (id, make, model, price) values (554, 'Toyota', 'Supra', 90);
insert into car (id, make, model, price) values (555, 'Volkswagen', 'Touareg', 42);
insert into car (id, make, model, price) values (556, 'Isuzu', 'Trooper', 94);
insert into car (id, make, model, price) values (557, 'Nissan', 'Sentra', 5);
insert into car (id, make, model, price) values (558, 'Lincoln', 'MKS', 90);
insert into car (id, make, model, price) values (559, 'BMW', '6 Series', 4);
insert into car (id, make, model, price) values (560, 'Hyundai', 'Tiburon', 6);
insert into car (id, make, model, price) values (561, 'Lincoln', 'Town Car', 58);
insert into car (id, make, model, price) values (562, 'GMC', 'Canyon', 15);
insert into car (id, make, model, price) values (563, 'Lexus', 'GS', 24);
insert into car (id, make, model, price) values (564, 'Dodge', 'Ram Wagon B350', 33);
insert into car (id, make, model, price) values (565, 'Mitsubishi', 'Chariot', 67);
insert into car (id, make, model, price) values (566, 'Aston Martin', 'DB9', 42);
insert into car (id, make, model, price) values (567, 'Dodge', 'Stratus', 79);
insert into car (id, make, model, price) values (568, 'BMW', '7 Series', 81);
insert into car (id, make, model, price) values (569, 'Dodge', 'Avenger', 1);
insert into car (id, make, model, price) values (570, 'Nissan', 'Altima', 3);
insert into car (id, make, model, price) values (571, 'Ford', 'F350', 88);
insert into car (id, make, model, price) values (572, 'Bentley', 'Continental GT', 49);
insert into car (id, make, model, price) values (573, 'Pontiac', 'Bonneville', 80);
insert into car (id, make, model, price) values (574, 'Pontiac', 'Grand Am', 77);
insert into car (id, make, model, price) values (575, 'Mercury', 'Milan', 23);
insert into car (id, make, model, price) values (576, 'Porsche', 'Panamera', 12);
insert into car (id, make, model, price) values (577, 'Toyota', 'Sienna', 55);
insert into car (id, make, model, price) values (578, 'GMC', 'Savana 1500', 69);
insert into car (id, make, model, price) values (579, 'Nissan', 'Altima', 1);
insert into car (id, make, model, price) values (580, 'Mercedes-Benz', 'S-Class', 75);
insert into car (id, make, model, price) values (581, 'Ford', 'Fusion', 36);
insert into car (id, make, model, price) values (582, 'Dodge', 'Daytona', 4);
insert into car (id, make, model, price) values (583, 'Pontiac', 'Bonneville', 42);
insert into car (id, make, model, price) values (584, 'Chevrolet', 'Metro', 89);
insert into car (id, make, model, price) values (585, 'Audi', 'A4', 84);
insert into car (id, make, model, price) values (586, 'Chrysler', 'Concorde', 70);
insert into car (id, make, model, price) values (587, 'Chevrolet', 'Suburban 1500', 29);
insert into car (id, make, model, price) values (588, 'Buick', 'Skylark', 99);
insert into car (id, make, model, price) values (589, 'Nissan', 'Maxima', 18);
insert into car (id, make, model, price) values (590, 'Toyota', 'Echo', 93);
insert into car (id, make, model, price) values (591, 'Maserati', 'Biturbo', 96);
insert into car (id, make, model, price) values (592, 'Bentley', 'Continental Flying Spur', 45);
insert into car (id, make, model, price) values (593, 'Mercedes-Benz', 'S-Class', 19);
insert into car (id, make, model, price) values (594, 'Audi', 'Allroad', 14);
insert into car (id, make, model, price) values (595, 'Volvo', 'S80', 67);
insert into car (id, make, model, price) values (596, 'Chevrolet', 'Camaro', 87);
insert into car (id, make, model, price) values (597, 'Mitsubishi', 'RVR', 37);
insert into car (id, make, model, price) values (598, 'Mitsubishi', 'Chariot', 89);
insert into car (id, make, model, price) values (599, 'GMC', 'Acadia', 18);
insert into car (id, make, model, price) values (600, 'BMW', '3 Series', 55);
insert into car (id, make, model, price) values (601, 'Toyota', 'Avalon', 68);
insert into car (id, make, model, price) values (602, 'Jaguar', 'S-Type', 88);
insert into car (id, make, model, price) values (603, 'Kia', 'Sorento', 13);
insert into car (id, make, model, price) values (604, 'Hyundai', 'Sonata', 79);
insert into car (id, make, model, price) values (605, 'Ford', 'Explorer Sport Trac', 72);
insert into car (id, make, model, price) values (606, 'Toyota', 'Supra', 20);
insert into car (id, make, model, price) values (607, 'Mazda', 'Protege', 36);
insert into car (id, make, model, price) values (608, 'Chevrolet', 'Silverado 2500', 96);
insert into car (id, make, model, price) values (609, 'Audi', 'A3', 19);
insert into car (id, make, model, price) values (610, 'Ford', 'Bronco II', 36);
insert into car (id, make, model, price) values (611, 'Saab', '900', 48);
insert into car (id, make, model, price) values (612, 'Ford', 'Aerostar', 23);
insert into car (id, make, model, price) values (613, 'Volkswagen', 'New Beetle', 8);
insert into car (id, make, model, price) values (614, 'Maserati', 'GranTurismo', 13);
insert into car (id, make, model, price) values (615, 'Ford', 'Econoline E150', 20);
insert into car (id, make, model, price) values (616, 'Chevrolet', 'Astro', 9);
insert into car (id, make, model, price) values (617, 'Buick', 'Regal', 47);
insert into car (id, make, model, price) values (618, 'Jeep', 'Liberty', 78);
insert into car (id, make, model, price) values (619, 'Suzuki', 'Forenza', 4);
insert into car (id, make, model, price) values (620, 'Chevrolet', 'Suburban 1500', 77);
insert into car (id, make, model, price) values (621, 'Infiniti', 'JX', 8);
insert into car (id, make, model, price) values (622, 'Suzuki', 'Aerio', 56);
insert into car (id, make, model, price) values (623, 'Volkswagen', 'Passat', 33);
insert into car (id, make, model, price) values (624, 'Infiniti', 'EX', 73);
insert into car (id, make, model, price) values (625, 'Audi', 'TT', 63);
insert into car (id, make, model, price) values (626, 'Mercury', 'Cougar', 28);
insert into car (id, make, model, price) values (627, 'Acura', 'RL', 26);
insert into car (id, make, model, price) values (628, 'Mazda', 'B-Series Plus', 100);
insert into car (id, make, model, price) values (629, 'Mercedes-Benz', 'CL-Class', 55);
insert into car (id, make, model, price) values (630, 'Mazda', 'MPV', 73);
insert into car (id, make, model, price) values (631, 'Audi', 'A8', 53);
insert into car (id, make, model, price) values (632, 'Ford', 'Expedition', 49);
insert into car (id, make, model, price) values (633, 'Ford', 'F450', 51);
insert into car (id, make, model, price) values (634, 'Toyota', 'Yaris', 34);
insert into car (id, make, model, price) values (635, 'Oldsmobile', 'Achieva', 42);
insert into car (id, make, model, price) values (636, 'Chevrolet', 'Blazer', 61);
insert into car (id, make, model, price) values (637, 'Volkswagen', 'GTI', 60);
insert into car (id, make, model, price) values (638, 'Ford', 'Econoline E350', 89);
insert into car (id, make, model, price) values (639, 'Dodge', 'Ram 3500', 95);
insert into car (id, make, model, price) values (640, 'Mercedes-Benz', '500SEL', 68);
insert into car (id, make, model, price) values (641, 'Mercedes-Benz', 'S-Class', 99);
insert into car (id, make, model, price) values (642, 'Subaru', 'Forester', 92);
insert into car (id, make, model, price) values (643, 'Chevrolet', 'Impala', 30);
insert into car (id, make, model, price) values (644, 'Infiniti', 'Q', 50);
insert into car (id, make, model, price) values (645, 'Volvo', 'S60', 52);
insert into car (id, make, model, price) values (646, 'Saab', '9000', 82);
insert into car (id, make, model, price) values (647, 'Oldsmobile', 'Achieva', 3);
insert into car (id, make, model, price) values (648, 'Chevrolet', 'Monte Carlo', 71);
insert into car (id, make, model, price) values (649, 'Lexus', 'LS Hybrid', 61);
insert into car (id, make, model, price) values (650, 'Mitsubishi', 'Chariot', 85);
insert into car (id, make, model, price) values (651, 'Cadillac', 'Eldorado', 100);
insert into car (id, make, model, price) values (652, 'Mercury', 'Milan', 95);
insert into car (id, make, model, price) values (653, 'BMW', 'X5', 60);
insert into car (id, make, model, price) values (654, 'Plymouth', 'Voyager', 87);
insert into car (id, make, model, price) values (655, 'Chevrolet', 'Impala', 29);
insert into car (id, make, model, price) values (656, 'Audi', '80', 24);
insert into car (id, make, model, price) values (657, 'Suzuki', 'XL7', 77);
insert into car (id, make, model, price) values (658, 'Dodge', 'Challenger', 40);
insert into car (id, make, model, price) values (659, 'Subaru', 'Loyale', 41);
insert into car (id, make, model, price) values (660, 'Ford', 'Focus', 15);
insert into car (id, make, model, price) values (661, 'Mitsubishi', 'Pajero', 87);
insert into car (id, make, model, price) values (662, 'Lexus', 'RX', 80);
insert into car (id, make, model, price) values (663, 'Saab', '900', 78);
insert into car (id, make, model, price) values (664, 'Volvo', 'XC90', 37);
insert into car (id, make, model, price) values (665, 'Hyundai', 'Veracruz', 13);
insert into car (id, make, model, price) values (666, 'Jeep', 'Grand Cherokee', 62);
insert into car (id, make, model, price) values (667, 'Saturn', 'VUE', 18);
insert into car (id, make, model, price) values (668, 'Scion', 'xD', 28);
insert into car (id, make, model, price) values (669, 'Pontiac', 'Aztek', 74);
insert into car (id, make, model, price) values (670, 'Mazda', 'B-Series', 72);
insert into car (id, make, model, price) values (671, 'Mercedes-Benz', '300CE', 22);
insert into car (id, make, model, price) values (672, 'BMW', '600', 59);
insert into car (id, make, model, price) values (673, 'Volkswagen', 'GTI', 29);
insert into car (id, make, model, price) values (674, 'Fiat', 'Nuova 500', 83);
insert into car (id, make, model, price) values (675, 'Saab', '9-2X', 83);
insert into car (id, make, model, price) values (676, 'Kia', 'Mohave/Borrego', 37);
insert into car (id, make, model, price) values (677, 'Dodge', 'Ram 3500', 67);
insert into car (id, make, model, price) values (678, 'Honda', 'Pilot', 65);
insert into car (id, make, model, price) values (679, 'Dodge', 'Grand Caravan', 52);
insert into car (id, make, model, price) values (680, 'Volkswagen', 'Touareg', 42);
insert into car (id, make, model, price) values (681, 'Infiniti', 'G', 52);
insert into car (id, make, model, price) values (682, 'Mercury', 'Mountaineer', 43);
insert into car (id, make, model, price) values (683, 'Chevrolet', 'TrailBlazer', 89);
insert into car (id, make, model, price) values (684, 'Buick', 'Century', 82);
insert into car (id, make, model, price) values (685, 'Mazda', 'Navajo', 34);
insert into car (id, make, model, price) values (686, 'Chevrolet', 'Sportvan G30', 91);
insert into car (id, make, model, price) values (687, 'Chevrolet', 'Lumina', 85);
insert into car (id, make, model, price) values (688, 'Mercury', 'Grand Marquis', 79);
insert into car (id, make, model, price) values (689, 'Bentley', 'Continental GTC', 94);
insert into car (id, make, model, price) values (690, 'Volvo', 'S70', 12);
insert into car (id, make, model, price) values (691, 'Hummer', 'H3T', 48);
insert into car (id, make, model, price) values (692, 'Mazda', '929', 36);
insert into car (id, make, model, price) values (693, 'Volkswagen', 'Jetta', 70);
insert into car (id, make, model, price) values (694, 'Mercury', 'Monterey', 29);
insert into car (id, make, model, price) values (695, 'Mazda', 'Protege', 44);
insert into car (id, make, model, price) values (696, 'Chevrolet', 'Express', 64);
insert into car (id, make, model, price) values (697, 'Dodge', 'Viper', 50);
insert into car (id, make, model, price) values (698, 'Mitsubishi', 'Precis', 84);
insert into car (id, make, model, price) values (699, 'Chrysler', '300', 25);
insert into car (id, make, model, price) values (700, 'Mitsubishi', 'Lancer', 59);
insert into car (id, make, model, price) values (701, 'Saturn', 'VUE', 3);
insert into car (id, make, model, price) values (702, 'Buick', 'Park Avenue', 81);
insert into car (id, make, model, price) values (703, 'Volkswagen', 'Jetta', 15);
insert into car (id, make, model, price) values (704, 'Mitsubishi', 'Eclipse', 11);
insert into car (id, make, model, price) values (705, 'Porsche', '944', 73);
insert into car (id, make, model, price) values (706, 'Saab', '9-5', 65);
insert into car (id, make, model, price) values (707, 'Bentley', 'Continental', 5);
insert into car (id, make, model, price) values (708, 'Ford', 'Thunderbird', 52);
insert into car (id, make, model, price) values (709, 'Ford', 'F150', 61);
insert into car (id, make, model, price) values (710, 'Pontiac', '6000', 68);
insert into car (id, make, model, price) values (711, 'Subaru', 'Forester', 52);
insert into car (id, make, model, price) values (712, 'Chevrolet', 'Astro', 10);
insert into car (id, make, model, price) values (713, 'Lotus', 'Elan', 58);
insert into car (id, make, model, price) values (714, 'Pontiac', 'Firefly', 89);
insert into car (id, make, model, price) values (715, 'Chrysler', 'Crossfire', 11);
insert into car (id, make, model, price) values (716, 'GMC', '3500', 23);
insert into car (id, make, model, price) values (717, 'Buick', 'Regal', 27);
insert into car (id, make, model, price) values (718, 'Pontiac', 'Safari', 19);
insert into car (id, make, model, price) values (719, 'Infiniti', 'G', 17);
insert into car (id, make, model, price) values (720, 'BMW', '7 Series', 54);
insert into car (id, make, model, price) values (721, 'Kia', 'Rio', 34);
insert into car (id, make, model, price) values (722, 'Mitsubishi', 'Pajero', 19);
insert into car (id, make, model, price) values (723, 'Ford', 'Mustang', 96);
insert into car (id, make, model, price) values (724, 'Chrysler', 'LHS', 49);
insert into car (id, make, model, price) values (725, 'Buick', 'LeSabre', 67);
insert into car (id, make, model, price) values (726, 'Buick', 'LeSabre', 56);
insert into car (id, make, model, price) values (727, 'Honda', 'S2000', 8);
insert into car (id, make, model, price) values (728, 'Nissan', 'Maxima', 96);
insert into car (id, make, model, price) values (729, 'Mazda', 'Mazda5', 6);
insert into car (id, make, model, price) values (730, 'Mitsubishi', 'Truck', 22);
insert into car (id, make, model, price) values (731, 'Spyker', 'C8', 80);
insert into car (id, make, model, price) values (732, 'BMW', '3 Series', 93);
insert into car (id, make, model, price) values (733, 'Pontiac', 'Grand Prix', 27);
insert into car (id, make, model, price) values (734, 'Nissan', 'Maxima', 100);
insert into car (id, make, model, price) values (735, 'Volkswagen', 'GTI', 26);
insert into car (id, make, model, price) values (736, 'Cadillac', 'Eldorado', 41);
insert into car (id, make, model, price) values (737, 'Chevrolet', 'Express 2500', 20);
insert into car (id, make, model, price) values (738, 'Volkswagen', 'GTI', 84);
insert into car (id, make, model, price) values (739, 'Pontiac', 'Fiero', 92);
insert into car (id, make, model, price) values (740, 'Suzuki', 'Aerio', 50);
insert into car (id, make, model, price) values (741, 'Volkswagen', 'Golf', 11);
insert into car (id, make, model, price) values (742, 'Audi', 'A4', 78);
insert into car (id, make, model, price) values (743, 'Toyota', 'RAV4', 34);
insert into car (id, make, model, price) values (744, 'Volvo', 'S60', 36);
insert into car (id, make, model, price) values (745, 'Dodge', 'Avenger', 82);
insert into car (id, make, model, price) values (746, 'Volkswagen', 'Jetta', 39);
insert into car (id, make, model, price) values (747, 'Buick', 'Rainier', 78);
insert into car (id, make, model, price) values (748, 'Mitsubishi', 'Montero Sport', 70);
insert into car (id, make, model, price) values (749, 'Honda', 'Civic', 20);
insert into car (id, make, model, price) values (750, 'Ford', 'Freestar', 44);
insert into car (id, make, model, price) values (751, 'Mercury', 'Mountaineer', 79);
insert into car (id, make, model, price) values (752, 'Buick', 'Electra', 100);
insert into car (id, make, model, price) values (753, 'Volvo', 'S60', 37);
insert into car (id, make, model, price) values (754, 'GMC', 'Yukon XL 1500', 24);
insert into car (id, make, model, price) values (755, 'Chevrolet', 'Silverado 1500', 39);
insert into car (id, make, model, price) values (756, 'Ford', 'Mustang', 90);
insert into car (id, make, model, price) values (757, 'Pontiac', 'Vibe', 67);
insert into car (id, make, model, price) values (758, 'Mazda', 'Miata MX-5', 4);
insert into car (id, make, model, price) values (759, 'Chevrolet', 'Sportvan G10', 64);
insert into car (id, make, model, price) values (760, 'Mazda', 'B-Series', 11);
insert into car (id, make, model, price) values (761, 'Mazda', 'B-Series', 59);
insert into car (id, make, model, price) values (762, 'Suzuki', 'Esteem', 54);
insert into car (id, make, model, price) values (763, 'Chevrolet', 'Blazer', 77);
insert into car (id, make, model, price) values (764, 'Dodge', 'Caravan', 90);
insert into car (id, make, model, price) values (765, 'Toyota', 'Tacoma', 4);
insert into car (id, make, model, price) values (766, 'Pontiac', 'Montana', 81);
insert into car (id, make, model, price) values (767, 'GMC', 'Canyon', 81);
insert into car (id, make, model, price) values (768, 'GMC', '1500', 56);
insert into car (id, make, model, price) values (769, 'Mitsubishi', 'Galant', 50);
insert into car (id, make, model, price) values (770, 'Audi', '4000s Quattro', 72);
insert into car (id, make, model, price) values (771, 'Oldsmobile', 'Achieva', 85);
insert into car (id, make, model, price) values (772, 'Hyundai', 'Tiburon', 100);
insert into car (id, make, model, price) values (773, 'Infiniti', 'G', 47);
insert into car (id, make, model, price) values (774, 'Nissan', '200SX', 4);
insert into car (id, make, model, price) values (775, 'Chevrolet', 'Express 3500', 18);
insert into car (id, make, model, price) values (776, 'Volkswagen', 'Eurovan', 25);
insert into car (id, make, model, price) values (777, 'Daewoo', 'Nubira', 1);
insert into car (id, make, model, price) values (778, 'Infiniti', 'QX', 48);
insert into car (id, make, model, price) values (779, 'Toyota', 'Previa', 87);
insert into car (id, make, model, price) values (780, 'Chevrolet', 'Camaro', 45);
insert into car (id, make, model, price) values (781, 'Suzuki', 'SX4', 31);
insert into car (id, make, model, price) values (782, 'Lincoln', 'Continental Mark VII', 12);
insert into car (id, make, model, price) values (783, 'Toyota', 'Echo', 67);
insert into car (id, make, model, price) values (784, 'Audi', 'S8', 96);
insert into car (id, make, model, price) values (785, 'Buick', 'Regal', 13);
insert into car (id, make, model, price) values (786, 'Buick', 'Regal', 34);
insert into car (id, make, model, price) values (787, 'Maybach', '57', 18);
insert into car (id, make, model, price) values (788, 'GMC', 'Sierra 3500', 20);
insert into car (id, make, model, price) values (789, 'Ford', 'Escort ZX2', 77);
insert into car (id, make, model, price) values (790, 'Ford', 'Thunderbird', 90);
insert into car (id, make, model, price) values (791, 'BMW', 'Z4', 8);
insert into car (id, make, model, price) values (792, 'MINI', 'Cooper Countryman', 44);
insert into car (id, make, model, price) values (793, 'Dodge', 'Ram Van 1500', 2);
insert into car (id, make, model, price) values (794, 'Cadillac', 'Catera', 44);
insert into car (id, make, model, price) values (795, 'Ford', 'Ranger', 51);
insert into car (id, make, model, price) values (796, 'Ford', 'Explorer', 51);
insert into car (id, make, model, price) values (797, 'Acura', 'SLX', 70);
insert into car (id, make, model, price) values (798, 'Volvo', 'XC60', 63);
insert into car (id, make, model, price) values (799, 'Pontiac', 'Trans Sport', 97);
insert into car (id, make, model, price) values (800, 'Chevrolet', 'Corsica', 51);
insert into car (id, make, model, price) values (801, 'GMC', 'Envoy', 77);
insert into car (id, make, model, price) values (802, 'Volvo', 'S40', 90);
insert into car (id, make, model, price) values (803, 'Infiniti', 'EX', 15);
insert into car (id, make, model, price) values (804, 'Chevrolet', 'Metro', 94);
insert into car (id, make, model, price) values (805, 'Land Rover', 'Freelander', 13);
insert into car (id, make, model, price) values (806, 'Ford', 'F250', 18);
insert into car (id, make, model, price) values (807, 'Toyota', 'Land Cruiser', 61);
insert into car (id, make, model, price) values (808, 'Subaru', 'Legacy', 74);
insert into car (id, make, model, price) values (809, 'Isuzu', 'Ascender', 76);
insert into car (id, make, model, price) values (810, 'GMC', 'Sierra', 78);
insert into car (id, make, model, price) values (811, 'Saab', '900', 2);
insert into car (id, make, model, price) values (812, 'BMW', 'M3', 8);
insert into car (id, make, model, price) values (813, 'Chevrolet', 'Corvette', 49);
insert into car (id, make, model, price) values (814, 'Land Rover', 'LR3', 99);
insert into car (id, make, model, price) values (815, 'Kia', 'Amanti', 44);
insert into car (id, make, model, price) values (816, 'Nissan', 'Quest', 19);
insert into car (id, make, model, price) values (817, 'Dodge', 'Ram', 16);
insert into car (id, make, model, price) values (818, 'Saab', '9-5', 100);
insert into car (id, make, model, price) values (819, 'Cadillac', 'Seville', 5);
insert into car (id, make, model, price) values (820, 'Isuzu', 'Trooper', 64);
insert into car (id, make, model, price) values (821, 'Kia', 'Spectra', 37);
insert into car (id, make, model, price) values (822, 'GMC', 'Yukon XL 2500', 93);
insert into car (id, make, model, price) values (823, 'Mercedes-Benz', 'Sprinter 2500', 85);
insert into car (id, make, model, price) values (824, 'Mercedes-Benz', 'S-Class', 33);
insert into car (id, make, model, price) values (825, 'Dodge', 'Caravan', 43);
insert into car (id, make, model, price) values (826, 'Acura', 'RL', 67);
insert into car (id, make, model, price) values (827, 'Chevrolet', 'Camaro', 58);
insert into car (id, make, model, price) values (828, 'Chevrolet', 'Silverado 3500', 98);
insert into car (id, make, model, price) values (829, 'Chevrolet', 'Lumina', 12);
insert into car (id, make, model, price) values (830, 'Hyundai', 'Genesis', 89);
insert into car (id, make, model, price) values (831, 'Volkswagen', 'Jetta', 4);
insert into car (id, make, model, price) values (832, 'Land Rover', 'Discovery Series II', 85);
insert into car (id, make, model, price) values (833, 'Porsche', 'Cayenne', 31);
insert into car (id, make, model, price) values (834, 'Audi', 'A6', 32);
insert into car (id, make, model, price) values (835, 'Volkswagen', 'Corrado', 98);
insert into car (id, make, model, price) values (836, 'Lexus', 'LS', 74);
insert into car (id, make, model, price) values (837, 'Austin', 'Mini Cooper', 57);
insert into car (id, make, model, price) values (838, 'Honda', 'Pilot', 28);
insert into car (id, make, model, price) values (839, 'Pontiac', 'GTO', 87);
insert into car (id, make, model, price) values (840, 'Chrysler', 'New Yorker', 19);
insert into car (id, make, model, price) values (841, 'Chevrolet', 'Monte Carlo', 80);
insert into car (id, make, model, price) values (842, 'Toyota', 'Tundra', 2);
insert into car (id, make, model, price) values (843, 'Lamborghini', 'Gallardo', 18);
insert into car (id, make, model, price) values (844, 'Jaguar', 'XK Series', 73);
insert into car (id, make, model, price) values (845, 'Chevrolet', 'Corsica', 2);
insert into car (id, make, model, price) values (846, 'Toyota', 'Yaris', 25);
insert into car (id, make, model, price) values (847, 'Toyota', 'Supra', 94);
insert into car (id, make, model, price) values (848, 'Plymouth', 'Colt', 50);
insert into car (id, make, model, price) values (849, 'Mercedes-Benz', 'SL-Class', 22);
insert into car (id, make, model, price) values (850, 'Dodge', 'Caravan', 76);
insert into car (id, make, model, price) values (851, 'Toyota', 'Avalon', 39);
insert into car (id, make, model, price) values (852, 'Chrysler', '300M', 32);
insert into car (id, make, model, price) values (853, 'Suzuki', 'Aerio', 32);
insert into car (id, make, model, price) values (854, 'Ford', 'Thunderbird', 72);
insert into car (id, make, model, price) values (855, 'GMC', 'Savana 2500', 40);
insert into car (id, make, model, price) values (856, 'Mercedes-Benz', 'C-Class', 87);
insert into car (id, make, model, price) values (857, 'Isuzu', 'Trooper', 80);
insert into car (id, make, model, price) values (858, 'Rolls-Royce', 'Phantom', 23);
insert into car (id, make, model, price) values (859, 'Mercedes-Benz', 'CLK-Class', 69);
insert into car (id, make, model, price) values (860, 'Volkswagen', 'Quantum', 98);
insert into car (id, make, model, price) values (861, 'Acura', 'SLX', 19);
insert into car (id, make, model, price) values (862, 'Mercury', 'Sable', 7);
insert into car (id, make, model, price) values (863, 'Daewoo', 'Lanos', 30);
insert into car (id, make, model, price) values (864, 'Ford', 'Focus', 6);
insert into car (id, make, model, price) values (865, 'Nissan', 'Xterra', 52);
insert into car (id, make, model, price) values (866, 'Saab', '900', 42);
insert into car (id, make, model, price) values (867, 'Nissan', 'Pathfinder', 22);
insert into car (id, make, model, price) values (868, 'Mazda', 'Mazda5', 78);
insert into car (id, make, model, price) values (869, 'GMC', 'Acadia', 58);
insert into car (id, make, model, price) values (870, 'Chevrolet', 'Tahoe', 30);
insert into car (id, make, model, price) values (871, 'BMW', '5 Series', 72);
insert into car (id, make, model, price) values (872, 'Porsche', 'Carrera GT', 38);
insert into car (id, make, model, price) values (873, 'Chevrolet', 'Monte Carlo', 81);
insert into car (id, make, model, price) values (874, 'Pontiac', 'Bonneville', 16);
insert into car (id, make, model, price) values (875, 'Maserati', 'Spyder', 43);
insert into car (id, make, model, price) values (876, 'Mazda', 'Mazdaspeed 3', 59);
insert into car (id, make, model, price) values (877, 'Chrysler', 'Concorde', 72);
insert into car (id, make, model, price) values (878, 'Audi', 'S4', 67);
insert into car (id, make, model, price) values (879, 'Cadillac', 'DeVille', 8);
insert into car (id, make, model, price) values (880, 'Mercury', 'Sable', 94);
insert into car (id, make, model, price) values (881, 'Mitsubishi', 'Mighty Max', 3);
insert into car (id, make, model, price) values (882, 'Cadillac', 'Eldorado', 49);
insert into car (id, make, model, price) values (883, 'Toyota', 'Camry', 20);
insert into car (id, make, model, price) values (884, 'Mercedes-Benz', 'E-Class', 17);
insert into car (id, make, model, price) values (885, 'Oldsmobile', 'Cutlass', 58);
insert into car (id, make, model, price) values (886, 'Buick', 'Lucerne', 30);
insert into car (id, make, model, price) values (887, 'GMC', '1500 Club Coupe', 13);
insert into car (id, make, model, price) values (888, 'Ford', 'Taurus', 71);
insert into car (id, make, model, price) values (889, 'Lamborghini', 'Murciélago', 32);
insert into car (id, make, model, price) values (890, 'GMC', 'Savana 1500', 58);
insert into car (id, make, model, price) values (891, 'Hyundai', 'Genesis Coupe', 93);
insert into car (id, make, model, price) values (892, 'Maserati', 'Biturbo', 23);
insert into car (id, make, model, price) values (893, 'Toyota', 'TundraMax', 62);
insert into car (id, make, model, price) values (894, 'Isuzu', 'Trooper', 42);
insert into car (id, make, model, price) values (895, 'Chevrolet', 'Equinox', 12);
insert into car (id, make, model, price) values (896, 'Lexus', 'IS-F', 42);
insert into car (id, make, model, price) values (897, 'Dodge', 'Ram 1500', 17);
insert into car (id, make, model, price) values (898, 'Geo', 'Tracker', 1);
insert into car (id, make, model, price) values (899, 'Volkswagen', 'GTI', 24);
insert into car (id, make, model, price) values (900, 'Land Rover', 'Discovery', 51);
insert into car (id, make, model, price) values (901, 'Citroën', 'SM', 80);
insert into car (id, make, model, price) values (902, 'Dodge', 'Viper', 37);
insert into car (id, make, model, price) values (903, 'Nissan', '280ZX', 21);
insert into car (id, make, model, price) values (904, 'Mazda', 'Millenia', 51);
insert into car (id, make, model, price) values (905, 'Volkswagen', 'Golf', 100);
insert into car (id, make, model, price) values (906, 'Volvo', '960', 55);
insert into car (id, make, model, price) values (907, 'Volkswagen', 'Jetta', 16);
insert into car (id, make, model, price) values (908, 'Mitsubishi', 'Expo', 16);
insert into car (id, make, model, price) values (909, 'Mazda', 'Miata MX-5', 61);
insert into car (id, make, model, price) values (910, 'Isuzu', 'Trooper', 12);
insert into car (id, make, model, price) values (911, 'Kia', 'Sportage', 1);
insert into car (id, make, model, price) values (912, 'Dodge', 'Ram 3500', 64);
insert into car (id, make, model, price) values (913, 'GMC', 'Savana 1500', 43);
insert into car (id, make, model, price) values (914, 'Scion', 'xB', 100);
insert into car (id, make, model, price) values (915, 'Mercedes-Benz', 'S-Class', 57);
insert into car (id, make, model, price) values (916, 'Lamborghini', 'Countach', 18);
insert into car (id, make, model, price) values (917, 'Porsche', 'Cayenne', 65);
insert into car (id, make, model, price) values (918, 'Ford', 'Excursion', 30);
insert into car (id, make, model, price) values (919, 'Honda', 'Civic', 35);
insert into car (id, make, model, price) values (920, 'Ford', 'F-Series', 47);
insert into car (id, make, model, price) values (921, 'BMW', 'M3', 23);
insert into car (id, make, model, price) values (922, 'Maybach', '57', 65);
insert into car (id, make, model, price) values (923, 'Infiniti', 'G', 81);
insert into car (id, make, model, price) values (924, 'Dodge', 'Ram Van 2500', 7);
insert into car (id, make, model, price) values (925, 'Buick', 'Electra', 63);
insert into car (id, make, model, price) values (926, 'Honda', 'Civic', 36);
insert into car (id, make, model, price) values (927, 'Chevrolet', 'Silverado 2500', 66);
insert into car (id, make, model, price) values (928, 'Honda', 'Accord', 14);
insert into car (id, make, model, price) values (929, 'Ford', 'F350', 36);
insert into car (id, make, model, price) values (930, 'Ford', 'Probe', 80);
insert into car (id, make, model, price) values (931, 'Mercury', 'Sable', 73);
insert into car (id, make, model, price) values (932, 'Ford', 'F250', 12);
insert into car (id, make, model, price) values (933, 'Chrysler', 'Cirrus', 69);
insert into car (id, make, model, price) values (934, 'Chevrolet', 'Camaro', 55);
insert into car (id, make, model, price) values (935, 'Ford', 'Probe', 65);
insert into car (id, make, model, price) values (936, 'Toyota', 'RAV4', 59);
insert into car (id, make, model, price) values (937, 'Lexus', 'ES', 5);
insert into car (id, make, model, price) values (938, 'Cadillac', 'STS', 66);
insert into car (id, make, model, price) values (939, 'Pontiac', 'GTO', 96);
insert into car (id, make, model, price) values (940, 'Scion', 'xD', 71);
insert into car (id, make, model, price) values (941, 'Ford', 'Econoline E350', 27);
insert into car (id, make, model, price) values (942, 'Land Rover', 'Discovery', 84);
insert into car (id, make, model, price) values (943, 'Buick', 'Park Avenue', 92);
insert into car (id, make, model, price) values (944, 'Maybach', '57', 47);
insert into car (id, make, model, price) values (945, 'Chevrolet', 'S10', 98);
insert into car (id, make, model, price) values (946, 'Chevrolet', 'Corvette', 36);
insert into car (id, make, model, price) values (947, 'Subaru', 'Forester', 10);
insert into car (id, make, model, price) values (948, 'Pontiac', 'LeMans', 46);
insert into car (id, make, model, price) values (949, 'Dodge', 'Viper', 14);
insert into car (id, make, model, price) values (950, 'Mitsubishi', 'Galant', 74);
insert into car (id, make, model, price) values (951, 'Morgan', 'Aero 8', 71);
insert into car (id, make, model, price) values (952, 'Chevrolet', 'Avalanche 1500', 64);
insert into car (id, make, model, price) values (953, 'Ford', 'Model T', 91);
insert into car (id, make, model, price) values (954, 'Mitsubishi', 'Eclipse', 25);
insert into car (id, make, model, price) values (955, 'Volvo', 'S40', 61);
insert into car (id, make, model, price) values (956, 'Lexus', 'GS', 17);
insert into car (id, make, model, price) values (957, 'Volkswagen', 'R32', 94);
insert into car (id, make, model, price) values (958, 'Infiniti', 'G35', 12);
insert into car (id, make, model, price) values (959, 'Lincoln', 'Navigator', 59);
insert into car (id, make, model, price) values (960, 'Chevrolet', 'G-Series G10', 46);
insert into car (id, make, model, price) values (961, 'Suzuki', 'SJ', 72);
insert into car (id, make, model, price) values (962, 'Ford', 'F150', 54);
insert into car (id, make, model, price) values (963, 'Ford', 'E350', 99);
insert into car (id, make, model, price) values (964, 'Toyota', 'Avalon', 38);
insert into car (id, make, model, price) values (965, 'Dodge', 'Stealth', 14);
insert into car (id, make, model, price) values (966, 'Cadillac', 'XLR-V', 40);
insert into car (id, make, model, price) values (967, 'Volvo', 'S60', 5);
insert into car (id, make, model, price) values (968, 'Mazda', 'B-Series', 48);
insert into car (id, make, model, price) values (969, 'Nissan', 'Sentra', 48);
insert into car (id, make, model, price) values (970, 'Ford', 'Expedition EL', 53);
insert into car (id, make, model, price) values (971, 'Hyundai', 'Azera', 53);
insert into car (id, make, model, price) values (972, 'Suzuki', 'Grand Vitara', 73);
insert into car (id, make, model, price) values (973, 'Geo', 'Tracker', 15);
insert into car (id, make, model, price) values (974, 'MINI', 'Cooper', 63);
insert into car (id, make, model, price) values (975, 'Nissan', '300ZX', 43);
insert into car (id, make, model, price) values (976, 'BMW', '5 Series', 67);
insert into car (id, make, model, price) values (977, 'Jeep', 'Cherokee', 90);
insert into car (id, make, model, price) values (978, 'Mercedes-Benz', 'CL-Class', 46);
insert into car (id, make, model, price) values (979, 'Pontiac', 'Montana SV6', 4);
insert into car (id, make, model, price) values (980, 'Ford', 'Taurus', 3);
insert into car (id, make, model, price) values (981, 'Hyundai', 'Santa Fe', 33);
insert into car (id, make, model, price) values (982, 'Honda', 'S2000', 47);
insert into car (id, make, model, price) values (983, 'Toyota', 'Sienna', 8);
insert into car (id, make, model, price) values (984, 'Jeep', 'Wrangler', 8);
insert into car (id, make, model, price) values (985, 'Oldsmobile', 'Cutlass', 38);
insert into car (id, make, model, price) values (986, 'Mercedes-Benz', 'S-Class', 14);
insert into car (id, make, model, price) values (987, 'Volkswagen', 'Cabriolet', 98);
insert into car (id, make, model, price) values (988, 'Honda', 'Insight', 28);
insert into car (id, make, model, price) values (989, 'GMC', 'Vandura G2500', 21);
insert into car (id, make, model, price) values (990, 'Mercury', 'Topaz', 9);
insert into car (id, make, model, price) values (991, 'Nissan', 'GT-R', 57);
insert into car (id, make, model, price) values (992, 'Acura', 'NSX', 75);
insert into car (id, make, model, price) values (993, 'Honda', 'Civic', 91);
insert into car (id, make, model, price) values (994, 'Suzuki', 'SJ', 84);
insert into car (id, make, model, price) values (995, 'Chevrolet', 'Equinox', 14);
insert into car (id, make, model, price) values (996, 'Chevrolet', 'Suburban 2500', 7);
insert into car (id, make, model, price) values (997, 'Pontiac', 'Bonneville', 89);
insert into car (id, make, model, price) values (998, 'Nissan', 'Murano', 52);
insert into car (id, make, model, price) values (999, 'Subaru', 'Tribeca', 22);
insert into car (id, make, model, price) values (1000, 'Acura', 'Integra', 48);
